cursor #e3e4cf
cursor_text_color #c7c8b4

foreground            #e3e4cf
background            #121408
selection_foreground  #253515
selection_background  #b9cda0
url_color             #b3d400

color0   #121408
color1   #fa2a07
color2   #15d400
color3   #ffd900
color4   #aac900
color5   #526200
color6   #b3d400
color7   #dadec3
color8   #868975
color9   #ff5a3f
color10  #5efe4c
color11  #ffe44c
color12  #cae922
color13  #e3ff4c
color14  #edff8c
color15  #fcfff2
