shell /usr/bin/fish

cursor            #a7c8ff
cursor_text_color #003060

foreground            #dee2ef
background            #090e17
selection_foreground  #272f4d
selection_background  #bec5eb
url_color             #bec5eb

#: black 000000 767676
color0  #0e141c
color8  #30353e
#: red cc0403 f2201f
color1  #0c4f72
color9  #2da9ea
#: green 19cb00 23fd00
color2  #bec5eb
color10 #dce1ff
#: yellow cecb00 fffd00
color3  #c6c0f9
color11 #e4dfff
#: blue 0d73cc 1a8fff
color4  #004787
color12 #a7c8ff
#: magenta cb1ed1 fd28ff
color5  #3e4565
color13 #bec5eb
#: cyan 0dcdcd 14ffff
color6  #454171
color14 #c6c0f9
#: white dddddd ffffff
color7  #c2c6d2
color15 #dee2ef

mark1_foreground #001c3b
mark1_background #d5e3ff
mark2_foreground #121a37
mark2_background #dce1ff
mark3_foreground #191443
mark3_background #e4dfff

active_tab_foreground #003060
active_tab_background #a7c8ff
inactive_tab_foreground #d5e3ff
inactive_tab_background #004787

active_border_color #a7c8ff
inactive_border_color #003060
# bell_border_color #ff5a00