[config]
version_check = false

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.lua'
output_path = '~/.config/hypr/hyprland/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

# VS Code matugen extension
[templates.vscode-raw]
input_path = './templates/vscode/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.discord]
input_path = './templates/discord/discord-matugen.css'
output_path = '~/.config/vesktop/themes/discord-matugen.css'

[templates.zen-userContent]
input_path = './templates/zen/userContent.css'
output_path = '~/.config/zen/pbkmoeqq.Default (release)/chrome/userContent.css'

[templates.zen-userStyles]
input_path = './templates/zen/userStyles.css'
output_path = '~/.config/zen/pbkmoeqq.Default (release)/chrome/userStyles.css'
