hl.on("hyprland.start", function()
  hl.exec_cmd(
  "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,pkcs11")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("otd-daemon")
  hl.exec_cmd("waybar")
  hl.exec_cmd("vicinae server")
end)
