require("nsh.variables")
require("nsh.autostart")
require("nsh.env")
require("nsh.monitor")
require("nsh.input")

require("nsh.keybinds.apps")
require("nsh.keybinds.multimidia")
require("nsh.keybinds.session")
require("nsh.keybinds.windows")
require("nsh.keybinds.workspaces")

require("nsh.general")
require("nsh.decoration")
require("nsh.animations")
require("nsh.rules")
require("nsh.matugen")
